export enum NAVIGATION {
    default = "/*",
    home = "/home",
    dashboard = "/dashboard",
    dietGenerator = "/diet/generator",
    myDiet = "/diet",
    newMeal = "/newMeal",
    profile = "/profile",
    forum = "/forum",
    forumPosts = "/forum/posts",
    forumMeals = "/forum/meals",
    forumMeal = "/forum/meals/meal",
    forumFeedbacks = "/forum/feedbacks",
    forumFeedback = "/forum/feedbacks/feedback",
    forumNewlyAddedMeals = "/forum/newlyAddedMeals",
    forumNewlyAddedMeal = "/forum/newlyAddedMeals/newlyAddedMeal",
    recipes = "/recipe",
    premium = "/premium",
}
