export enum NAVIGATION {
    default = "/*",
    home = "/home",
    dashboard = "/dashboard",
    dietGenerator = "/diet/generator",
    myDiet = "/diet",
    myMeals = "/meals",
    newMeal = "/newMeal",
    basicUserProfile = "/profile",
    forum = "/forum",
    forumPosts = "/forum/posts",
    forumPost = "/forum/posts/post",
    forumMeals = "/forum/newMeals",
    forumMeal = "/forum/newMeals/newMeal",
    forumFeedbacks = "/forum/feedbacks",
    forumFeedback = "/forum/feedbacks/feedback",
    forumNewlyAddedMeals = "/forum/newlyAddedMeals",
    forumNewlyAddedMeal = "/forum/newlyAddedMeals/newlyAddedMeal",
    expandedUserProfile = "/profile/expanded",
    recipe = "/recipe",
    premium = "/premium",
    payment = "/payment",
    exclusions = "/exclusions",
}
